//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCCIFinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectData
    {
        public int ProjectID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectDescription { get; set; }
        public string Language { get; set; }
        public string ImageLink { get; set; }
        public string GitHub { get; set; }
        public string Collaborators { get; set; }
    }
}
